[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CodecBzip2 = "523fee87-0ab8-5b00-afb7-3ecf72e48cfd"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
HSL = "34c5aeac-e683-54a6-a0e9-6e0fdc586c50"
HSL_jll = "017b0a0e-03f4-516a-9b91-836bbd1904dd"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
MadNLPGPU = "d72a61cc-809d-412f-99be-fd81f4b8a598"
MadNLPHSL = "7fb6135f-58fe-4112-84ca-653cf5be0c77"
MadQP = "4406d55e-1099-4ca6-ac6a-6cf051b10024"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
QPSReader = "10f199a5-22af-520b-b891-7ce84a7b1bd0"
QuadraticModels = "f468eda6-eac5-11e8-05a5-ff9e497bcd19"

[compat]
CUDA = "5.8.1"
CodecBzip2 = "0.8.5"
DelimitedFiles = "1.9.1"
GZip = "0.6.2"
HSL = "0.5.1"
KernelAbstractions = "0.9.34"
MadNLP = "0.8.7"
MadNLPGPU = "0.7.7"
MadNLPHSL = "0.6.0"
MadQP = "0.1.0"
NLPModels = "0.21.5"
QPSReader = "0.2.1"
QuadraticModels = "0.9.13"
